// <auto-generated />
using CatalogService.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.DAL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251102111631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.Composition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Compositions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 3600.0,
                            Genre = "Classical",
                            Title = "Symphony No. 5"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 1800.0,
                            Genre = "Jazz",
                            Title = "Jazz Improvisation"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ConcertProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompositionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompositionId1")
                        .HasColumnType("integer");

                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId");

                    b.HasIndex("CompositionId1");

                    b.HasIndex("ConcertId", "CompositionId")
                        .IsUnique();

                    b.ToTable("ConcertPrograms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompositionId = 1,
                            ConcertId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompositionId = 2,
                            ConcertId = 1
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Instruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instrument_Price", "\"Price\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Violin",
                            Price = 1200m,
                            Type = "String"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trumpet",
                            Price = 900m,
                            Type = "Brass"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drum",
                            Price = 1500m,
                            Type = "Percussion"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.InstrumentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("InstrumentImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstrumentId = 1,
                            Url = "violin.jpg"
                        },
                        new
                        {
                            Id = 2,
                            InstrumentId = 2,
                            Url = "trumpet.jpg"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Performers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstrumentId = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            InstrumentId = 2,
                            Name = "Maria Smith"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ConcertProgram", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Composition", "Composition")
                        .WithMany()
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.Composition", null)
                        .WithMany("ConcertPrograms")
                        .HasForeignKey("CompositionId1");

                    b.Navigation("Composition");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.InstrumentImage", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Instrument", "Instrument")
                        .WithOne("InstrumentImage")
                        .HasForeignKey("CatalogService.Domain.Entities.InstrumentImage", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Performer", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Performers")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Composition", b =>
                {
                    b.Navigation("ConcertPrograms");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("InstrumentImage");

                    b.Navigation("Performers");
                });
#pragma warning restore 612, 618
        }
    }
}
